---
default_install_hook_types: [pre-commit, pre-push, commit-msg]

files: .*

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
  - id: prettier
    stages: [pre-commit]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
